# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_sikuli', [dirname(__file__)])
        except ImportError:
            import _sikuli
            return _sikuli
        if fp is not None:
            try:
                _mod = imp.load_module('_sikuli', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _sikuli = swig_import_helper()
    del swig_import_helper
else:
    import _sikuli
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


try:
    import weakref
    weakref_proxy = weakref.proxy
except:
    weakref_proxy = lambda x: x


_type = type
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
   if (name == "thisown"): return self.this.own(value)
   if (name == "this"):
      if _type(value).__name__ == 'SwigPyObject':
         self.__dict__[name] = value
         return
   method = class_type.__swig_setmethods__.get(name,None)
   if method: return method(self,value)
   if (not static) or hasattr(self,name):
      self.__dict__[name] = value
   else:
      raise AttributeError("You cannot add attributes to %s" % self)   

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _sikuli.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _sikuli.SwigPyIterator_value(self)
    def incr(self, n = 1): return _sikuli.SwigPyIterator_incr(self, n)
    def decr(self, n = 1): return _sikuli.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _sikuli.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _sikuli.SwigPyIterator_equal(self, *args)
    def copy(self): return _sikuli.SwigPyIterator_copy(self)
    def next(self): return _sikuli.SwigPyIterator_next(self)
    def __next__(self): return _sikuli.SwigPyIterator___next__(self)
    def previous(self): return _sikuli.SwigPyIterator_previous(self)
    def advance(self, *args): return _sikuli.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _sikuli.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _sikuli.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _sikuli.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _sikuli.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _sikuli.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _sikuli.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _sikuli.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class Matches(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Matches, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Matches, name)
    __repr__ = _swig_repr
    def iterator(self): return _sikuli.Matches_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _sikuli.Matches___nonzero__(self)
    def __bool__(self): return _sikuli.Matches___bool__(self)
    def __len__(self): return _sikuli.Matches___len__(self)
    def pop(self): return _sikuli.Matches_pop(self)
    def __getslice__(self, *args): return _sikuli.Matches___getslice__(self, *args)
    def __setslice__(self, *args): return _sikuli.Matches___setslice__(self, *args)
    def __delslice__(self, *args): return _sikuli.Matches___delslice__(self, *args)
    def __delitem__(self, *args): return _sikuli.Matches___delitem__(self, *args)
    def __getitem__(self, *args): return _sikuli.Matches___getitem__(self, *args)
    def __setitem__(self, *args): return _sikuli.Matches___setitem__(self, *args)
    def append(self, *args): return _sikuli.Matches_append(self, *args)
    def empty(self): return _sikuli.Matches_empty(self)
    def size(self): return _sikuli.Matches_size(self)
    def clear(self): return _sikuli.Matches_clear(self)
    def swap(self, *args): return _sikuli.Matches_swap(self, *args)
    def get_allocator(self): return _sikuli.Matches_get_allocator(self)
    def begin(self): return _sikuli.Matches_begin(self)
    def end(self): return _sikuli.Matches_end(self)
    def rbegin(self): return _sikuli.Matches_rbegin(self)
    def rend(self): return _sikuli.Matches_rend(self)
    def pop_back(self): return _sikuli.Matches_pop_back(self)
    def erase(self, *args): return _sikuli.Matches_erase(self, *args)
    def __init__(self, *args): 
        this = _sikuli.new_Matches(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _sikuli.Matches_push_back(self, *args)
    def front(self): return _sikuli.Matches_front(self)
    def back(self): return _sikuli.Matches_back(self)
    def assign(self, *args): return _sikuli.Matches_assign(self, *args)
    def resize(self, *args): return _sikuli.Matches_resize(self, *args)
    def insert(self, *args): return _sikuli.Matches_insert(self, *args)
    def reserve(self, *args): return _sikuli.Matches_reserve(self, *args)
    def capacity(self): return _sikuli.Matches_capacity(self)
    __swig_destroy__ = _sikuli.delete_Matches
    __del__ = lambda self : None;
Matches_swigregister = _sikuli.Matches_swigregister
Matches_swigregister(Matches)


def initOCR(*args):
  return _sikuli.initOCR(*args)
initOCR = _sikuli.initOCR

def switchApp(*args):
  return _sikuli.switchApp(*args)
switchApp = _sikuli.switchApp

def addImagePath(*args):
  return _sikuli.addImagePath(*args)
addImagePath = _sikuli.addImagePath

def wait(*args):
  return _sikuli.wait(*args)
wait = _sikuli.wait
ALT = _sikuli.ALT
CMD = _sikuli.CMD
CTRL = _sikuli.CTRL
META = _sikuli.META
SHIFT = _sikuli.SHIFT
WIN = _sikuli.WIN
ENTER = _sikuli.ENTER
TAB = _sikuli.TAB
ESC = _sikuli.ESC
INSERT = _sikuli.INSERT
BACKSPACE = _sikuli.BACKSPACE
DELETE = _sikuli.DELETE
CAPSLOCK = _sikuli.CAPSLOCK
SPACE = _sikuli.SPACE
F1 = _sikuli.F1
F2 = _sikuli.F2
F3 = _sikuli.F3
F4 = _sikuli.F4
F5 = _sikuli.F5
F6 = _sikuli.F6
F7 = _sikuli.F7
F8 = _sikuli.F8
F9 = _sikuli.F9
F10 = _sikuli.F10
F11 = _sikuli.F11
F12 = _sikuli.F12
F13 = _sikuli.F13
F14 = _sikuli.F14
F15 = _sikuli.F15
HOME = _sikuli.HOME
END = _sikuli.END
LEFT = _sikuli.LEFT
RIGHT = _sikuli.RIGHT
DOWN = _sikuli.DOWN
UP = _sikuli.UP
PAGE_DOWN = _sikuli.PAGE_DOWN
PAGE_UP = _sikuli.PAGE_UP
ANYWHERE = _sikuli.ANYWHERE
TOPMOST = _sikuli.TOPMOST
BOTTOMMOST = _sikuli.BOTTOMMOST
LEFTMOST = _sikuli.LEFTMOST
RIGHTMOST = _sikuli.RIGHTMOST
SCORE = _sikuli.SCORE
TOPDOWN = _sikuli.TOPDOWN
BOTTOMUP = _sikuli.BOTTOMUP
LEFTRIGHT = _sikuli.LEFTRIGHT
RIGHTLEFT = _sikuli.RIGHTLEFT
class Pattern(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Pattern, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Pattern, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _sikuli.new_Pattern(*args)
        try: self.this.append(this)
        except: self.this = this
    def all(self): return _sikuli.Pattern_all(self)
    def one(self): return _sikuli.Pattern_one(self)
    def similar(self, *args): return _sikuli.Pattern_similar(self, *args)
    def exact(self): return _sikuli.Pattern_exact(self)
    def targetOffset(self, *args): return _sikuli.Pattern_targetOffset(self, *args)
    def getTargetOffset(self): return _sikuli.Pattern_getTargetOffset(self)
    def getSimilarity(self): return _sikuli.Pattern_getSimilarity(self)
    def topMost(self): return _sikuli.Pattern_topMost(self)
    def bottomMost(self): return _sikuli.Pattern_bottomMost(self)
    def leftMost(self): return _sikuli.Pattern_leftMost(self)
    def rightMost(self): return _sikuli.Pattern_rightMost(self)
    def limit(self, *args): return _sikuli.Pattern_limit(self, *args)
    def order(self, *args): return _sikuli.Pattern_order(self, *args)
    def toString(self): return _sikuli.Pattern_toString(self)
    def getText(self): return _sikuli.Pattern_getText(self)
    def getImageURL(self): return _sikuli.Pattern_getImageURL(self)
    def isImageURL(self): return _sikuli.Pattern_isImageURL(self)
    def isText(self): return _sikuli.Pattern_isText(self)
    def bAll(self): return _sikuli.Pattern_bAll(self)
    def bOne(self): return _sikuli.Pattern_bOne(self)
    def where(self): return _sikuli.Pattern_where(self)
    def getOrdering(self): return _sikuli.Pattern_getOrdering(self)
    def getLimit(self): return _sikuli.Pattern_getLimit(self)
    __swig_destroy__ = _sikuli.delete_Pattern
    __del__ = lambda self : None;
Pattern_swigregister = _sikuli.Pattern_swigregister
Pattern_swigregister(Pattern)

class Location(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Location, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Location, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _sikuli.new_Location(*args)
        try: self.this.append(this)
        except: self.this = this
    def offset(self, *args): return _sikuli.Location_offset(self, *args)
    def left(self, *args): return _sikuli.Location_left(self, *args)
    def right(self, *args): return _sikuli.Location_right(self, *args)
    def above(self, *args): return _sikuli.Location_above(self, *args)
    def below(self, *args): return _sikuli.Location_below(self, *args)
    __swig_setmethods__["x"] = _sikuli.Location_x_set
    __swig_getmethods__["x"] = _sikuli.Location_x_get
    if _newclass:x = _swig_property(_sikuli.Location_x_get, _sikuli.Location_x_set)
    __swig_setmethods__["y"] = _sikuli.Location_y_set
    __swig_getmethods__["y"] = _sikuli.Location_y_get
    if _newclass:y = _swig_property(_sikuli.Location_y_get, _sikuli.Location_y_set)
    __swig_setmethods__["screen"] = _sikuli.Location_screen_set
    __swig_getmethods__["screen"] = _sikuli.Location_screen_get
    if _newclass:screen = _swig_property(_sikuli.Location_screen_get, _sikuli.Location_screen_set)
    __swig_destroy__ = _sikuli.delete_Location
    __del__ = lambda self : None;
Location_swigregister = _sikuli.Location_swigregister
Location_swigregister(Location)

class Rectangle(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Rectangle, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Rectangle, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _sikuli.new_Rectangle(*args)
        try: self.this.append(this)
        except: self.this = this
    def intersection(self, *args): return _sikuli.Rectangle_intersection(self, *args)
    def toString(self): return _sikuli.Rectangle_toString(self)
    __swig_setmethods__["x"] = _sikuli.Rectangle_x_set
    __swig_getmethods__["x"] = _sikuli.Rectangle_x_get
    if _newclass:x = _swig_property(_sikuli.Rectangle_x_get, _sikuli.Rectangle_x_set)
    __swig_setmethods__["y"] = _sikuli.Rectangle_y_set
    __swig_getmethods__["y"] = _sikuli.Rectangle_y_get
    if _newclass:y = _swig_property(_sikuli.Rectangle_y_get, _sikuli.Rectangle_y_set)
    __swig_setmethods__["w"] = _sikuli.Rectangle_w_set
    __swig_getmethods__["w"] = _sikuli.Rectangle_w_get
    if _newclass:w = _swig_property(_sikuli.Rectangle_w_get, _sikuli.Rectangle_w_set)
    __swig_setmethods__["h"] = _sikuli.Rectangle_h_set
    __swig_getmethods__["h"] = _sikuli.Rectangle_h_get
    if _newclass:h = _swig_property(_sikuli.Rectangle_h_get, _sikuli.Rectangle_h_set)
    __swig_destroy__ = _sikuli.delete_Rectangle
    __del__ = lambda self : None;
Rectangle_swigregister = _sikuli.Rectangle_swigregister
Rectangle_swigregister(Rectangle)

class ScreenImage(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ScreenImage, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ScreenImage, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _sikuli.new_ScreenImage(*args)
        try: self.this.append(this)
        except: self.this = this
    def getROI(self): return _sikuli.ScreenImage_getROI(self)
    def getFilename(self): return _sikuli.ScreenImage_getFilename(self)
    def getMat(self): return _sikuli.ScreenImage_getMat(self)
    __swig_destroy__ = _sikuli.delete_ScreenImage
    __del__ = lambda self : None;
ScreenImage_swigregister = _sikuli.ScreenImage_swigregister
ScreenImage_swigregister(ScreenImage)

PADDING = _sikuli.PADDING
class Region(Rectangle):
    __swig_setmethods__ = {}
    for _s in [Rectangle]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Region, name, value)
    __swig_getmethods__ = {}
    for _s in [Rectangle]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Region, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _sikuli.new_Region(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _sikuli.delete_Region
    __del__ = lambda self : None;
    def getX(self): return _sikuli.Region_getX(self)
    def getY(self): return _sikuli.Region_getY(self)
    def getW(self): return _sikuli.Region_getW(self)
    def getH(self): return _sikuli.Region_getH(self)
    def setX(self, *args): return _sikuli.Region_setX(self, *args)
    def setY(self, *args): return _sikuli.Region_setY(self, *args)
    def setW(self, *args): return _sikuli.Region_setW(self, *args)
    def setH(self, *args): return _sikuli.Region_setH(self, *args)
    def __eq__(self, *args): return _sikuli.Region___eq__(self, *args)
    def getCenter(self): return _sikuli.Region_getCenter(self)
    def getLastMatch(self): return _sikuli.Region_getLastMatch(self)
    def getLastMatches(self): return _sikuli.Region_getLastMatches(self)
    def setLastMatch(self, *args): return _sikuli.Region_setLastMatch(self, *args)
    def setLastMatches(self, *args): return _sikuli.Region_setLastMatches(self, *args)
    def find(self, *args): return _sikuli.Region_find(self, *args)
    def findAll(self, *args): return _sikuli.Region_findAll(self, *args)
    def wait(self, *args): return _sikuli.Region_wait(self, *args)
    def exists(self, *args): return _sikuli.Region_exists(self, *args)
    def waitVanish(self, *args): return _sikuli.Region_waitVanish(self, *args)
    def findNow(self, *args): return _sikuli.Region_findNow(self, *args)
    def findAllNow(self, *args): return _sikuli.Region_findAllNow(self, *args)
    def waitAll(self, *args): return _sikuli.Region_waitAll(self, *args)
    def click(self, *args): return _sikuli.Region_click(self, *args)
    def doubleClick(self, *args): return _sikuli.Region_doubleClick(self, *args)
    def rightClick(self, *args): return _sikuli.Region_rightClick(self, *args)
    def hover(self, *args): return _sikuli.Region_hover(self, *args)
    def dragDrop(self, *args): return _sikuli.Region_dragDrop(self, *args)
    def drag(self, *args): return _sikuli.Region_drag(self, *args)
    def dropAt(self, *args): return _sikuli.Region_dropAt(self, *args)
    def type(self, *args): return _sikuli.Region_type(self, *args)
    def press(self, *args): return _sikuli.Region_press(self, *args)
    def paste(self, *args): return _sikuli.Region_paste(self, *args)
    def mouseDown(self, *args): return _sikuli.Region_mouseDown(self, *args)
    def mouseUp(self, *args): return _sikuli.Region_mouseUp(self, *args)
    def keyDown(self, *args): return _sikuli.Region_keyDown(self, *args)
    def keyUp(self, *args): return _sikuli.Region_keyUp(self, *args)
    def capture(self): return _sikuli.Region_capture(self)
    def nearby(self, *args): return _sikuli.Region_nearby(self, *args)
    def right(self, *args): return _sikuli.Region_right(self, *args)
    def left(self, *args): return _sikuli.Region_left(self, *args)
    def above(self, *args): return _sikuli.Region_above(self, *args)
    def below(self, *args): return _sikuli.Region_below(self, *args)
    def wider(self, range = 9999999): return _sikuli.Region_wider(self, range)
    def taller(self, range = 9999999): return _sikuli.Region_taller(self, range)
    def inside(self): return _sikuli.Region_inside(self)
    def inner(self, *args): return _sikuli.Region_inner(self, *args)
    def onAppear(self, *args): return _sikuli.Region_onAppear(self, *args)
    def onVanish(self, *args): return _sikuli.Region_onVanish(self, *args)
    def onChange(self, *args): return _sikuli.Region_onChange(self, *args)
Region_swigregister = _sikuli.Region_swigregister
Region_swigregister(Region)

class Match(Region):
    __swig_setmethods__ = {}
    for _s in [Region]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Match, name, value)
    __swig_getmethods__ = {}
    for _s in [Region]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Match, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _sikuli.delete_Match
    __del__ = lambda self : None;
    def __init__(self, *args): 
        this = _sikuli.new_Match(*args)
        try: self.this.append(this)
        except: self.this = this
    def compareTo(self, *args): return _sikuli.Match_compareTo(self, *args)
    def getTarget(self): return _sikuli.Match_getTarget(self)
    def getScore(self): return _sikuli.Match_getScore(self)
    def setTargetOffset(self, *args): return _sikuli.Match_setTargetOffset(self, *args)
Match_swigregister = _sikuli.Match_swigregister
Match_swigregister(Match)

class Screen(Region):
    __swig_setmethods__ = {}
    for _s in [Region]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Screen, name, value)
    __swig_getmethods__ = {}
    for _s in [Region]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Screen, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _sikuli.new_Screen(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _sikuli.delete_Screen
    __del__ = lambda self : None;
Screen_swigregister = _sikuli.Screen_swigregister
Screen_swigregister(Screen)

class Settings(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Settings, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Settings, name)
    __repr__ = _swig_repr
    __swig_setmethods__["DelayAfterDrag"] = _sikuli.Settings_DelayAfterDrag_set
    __swig_getmethods__["DelayAfterDrag"] = _sikuli.Settings_DelayAfterDrag_get
    if _newclass:DelayAfterDrag = _swig_property(_sikuli.Settings_DelayAfterDrag_get, _sikuli.Settings_DelayAfterDrag_set)
    __swig_setmethods__["DelayBeforeDrop"] = _sikuli.Settings_DelayBeforeDrop_set
    __swig_getmethods__["DelayBeforeDrop"] = _sikuli.Settings_DelayBeforeDrop_get
    if _newclass:DelayBeforeDrop = _swig_property(_sikuli.Settings_DelayBeforeDrop_get, _sikuli.Settings_DelayBeforeDrop_set)
    __swig_setmethods__["WaitScanRate"] = _sikuli.Settings_WaitScanRate_set
    __swig_getmethods__["WaitScanRate"] = _sikuli.Settings_WaitScanRate_get
    if _newclass:WaitScanRate = _swig_property(_sikuli.Settings_WaitScanRate_get, _sikuli.Settings_WaitScanRate_set)
    __swig_setmethods__["ThrowException"] = _sikuli.Settings_ThrowException_set
    __swig_getmethods__["ThrowException"] = _sikuli.Settings_ThrowException_get
    if _newclass:ThrowException = _swig_property(_sikuli.Settings_ThrowException_get, _sikuli.Settings_ThrowException_set)
    __swig_setmethods__["AutoWaitTimeout"] = _sikuli.Settings_AutoWaitTimeout_set
    __swig_getmethods__["AutoWaitTimeout"] = _sikuli.Settings_AutoWaitTimeout_get
    if _newclass:AutoWaitTimeout = _swig_property(_sikuli.Settings_AutoWaitTimeout_get, _sikuli.Settings_AutoWaitTimeout_set)
    __swig_getmethods__["addImagePath"] = lambda x: _sikuli.Settings_addImagePath
    if _newclass:addImagePath = staticmethod(_sikuli.Settings_addImagePath)
    __swig_getmethods__["getImagePaths"] = lambda x: _sikuli.Settings_getImagePaths
    if _newclass:getImagePaths = staticmethod(_sikuli.Settings_getImagePaths)
    __swig_getmethods__["resetImagePaths"] = lambda x: _sikuli.Settings_resetImagePaths
    if _newclass:resetImagePaths = staticmethod(_sikuli.Settings_resetImagePaths)
    def __init__(self): 
        this = _sikuli.new_Settings()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _sikuli.delete_Settings
    __del__ = lambda self : None;
Settings_swigregister = _sikuli.Settings_swigregister
Settings_swigregister(Settings)
cvar = _sikuli.cvar

def Settings_addImagePath(*args):
  return _sikuli.Settings_addImagePath(*args)
Settings_addImagePath = _sikuli.Settings_addImagePath

def Settings_getImagePaths():
  return _sikuli.Settings_getImagePaths()
Settings_getImagePaths = _sikuli.Settings_getImagePaths

def Settings_resetImagePaths():
  return _sikuli.Settings_resetImagePaths()
Settings_resetImagePaths = _sikuli.Settings_resetImagePaths

class FindFailed(Exception):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FindFailed, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FindFailed, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _sikuli.new_FindFailed(*args)
        try: self.this.append(this)
        except: self.this = this
    def what(self): return _sikuli.FindFailed_what(self)
    __swig_destroy__ = _sikuli.delete_FindFailed
    __del__ = lambda self : None;
FindFailed_swigregister = _sikuli.FindFailed_swigregister
FindFailed_swigregister(FindFailed)

class FileNotFound(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FileNotFound, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FileNotFound, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _sikuli.new_FileNotFound(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _sikuli.delete_FileNotFound
    __del__ = lambda self : None;
    def what(self): return _sikuli.FileNotFound_what(self)
FileNotFound_swigregister = _sikuli.FileNotFound_swigregister
FileNotFound_swigregister(FileNotFound)

class Event(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Event, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Event, name)
    __repr__ = _swig_repr
    __swig_setmethods__["type"] = _sikuli.Event_type_set
    __swig_getmethods__["type"] = _sikuli.Event_type_get
    if _newclass:type = _swig_property(_sikuli.Event_type_get, _sikuli.Event_type_set)
    __swig_setmethods__["pattern"] = _sikuli.Event_pattern_set
    __swig_getmethods__["pattern"] = _sikuli.Event_pattern_get
    if _newclass:pattern = _swig_property(_sikuli.Event_pattern_get, _sikuli.Event_pattern_set)
    __swig_setmethods__["match"] = _sikuli.Event_match_set
    __swig_getmethods__["match"] = _sikuli.Event_match_get
    if _newclass:match = _swig_property(_sikuli.Event_match_get, _sikuli.Event_match_set)
    __swig_setmethods__["region"] = _sikuli.Event_region_set
    __swig_getmethods__["region"] = _sikuli.Event_region_get
    if _newclass:region = _swig_property(_sikuli.Event_region_get, _sikuli.Event_region_set)
    def __init__(self): 
        this = _sikuli.new_Event()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _sikuli.delete_Event
    __del__ = lambda self : None;
Event_swigregister = _sikuli.Event_swigregister
Event_swigregister(Event)

APPEAR = _sikuli.APPEAR
VANISH = _sikuli.VANISH
CHANGE = _sikuli.CHANGE
class SikuliEventHandler(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SikuliEventHandler, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SikuliEventHandler, name)
    __repr__ = _swig_repr
    def __init__(self): 
        if self.__class__ == SikuliEventHandler:
            _self = None
        else:
            _self = self
        this = _sikuli.new_SikuliEventHandler(_self, )
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _sikuli.delete_SikuliEventHandler
    __del__ = lambda self : None;
    def handle(self, *args): return _sikuli.SikuliEventHandler_handle(self, *args)
    def __disown__(self):
        self.this.disown()
        _sikuli.disown_SikuliEventHandler(self)
        return weakref_proxy(self)
SikuliEventHandler_swigregister = _sikuli.SikuliEventHandler_swigregister
SikuliEventHandler_swigregister(SikuliEventHandler)

class Observer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Observer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Observer, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _sikuli.new_Observer(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _sikuli.delete_Observer
    __del__ = lambda self : None;
    __swig_setmethods__["event_type"] = _sikuli.Observer_event_type_set
    __swig_getmethods__["event_type"] = _sikuli.Observer_event_type_get
    if _newclass:event_type = _swig_property(_sikuli.Observer_event_type_get, _sikuli.Observer_event_type_set)
    __swig_setmethods__["pattern"] = _sikuli.Observer_pattern_set
    __swig_getmethods__["pattern"] = _sikuli.Observer_pattern_get
    if _newclass:pattern = _swig_property(_sikuli.Observer_pattern_get, _sikuli.Observer_pattern_set)
    __swig_setmethods__["callback"] = _sikuli.Observer_callback_set
    __swig_getmethods__["callback"] = _sikuli.Observer_callback_get
    if _newclass:callback = _swig_property(_sikuli.Observer_callback_get, _sikuli.Observer_callback_set)
    __swig_setmethods__["event_handler"] = _sikuli.Observer_event_handler_set
    __swig_getmethods__["event_handler"] = _sikuli.Observer_event_handler_get
    if _newclass:event_handler = _swig_property(_sikuli.Observer_event_handler_get, _sikuli.Observer_event_handler_set)
    __swig_setmethods__["active"] = _sikuli.Observer_active_set
    __swig_getmethods__["active"] = _sikuli.Observer_active_get
    if _newclass:active = _swig_property(_sikuli.Observer_active_get, _sikuli.Observer_active_set)
Observer_swigregister = _sikuli.Observer_swigregister
Observer_swigregister(Observer)

class RegionObserver(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RegionObserver, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RegionObserver, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _sikuli.new_RegionObserver(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _sikuli.delete_RegionObserver
    __del__ = lambda self : None;
    def addObserver(self, *args): return _sikuli.RegionObserver_addObserver(self, *args)
    def observe(self): return _sikuli.RegionObserver_observe(self)
    def getRegion(self): return _sikuli.RegionObserver_getRegion(self)
RegionObserver_swigregister = _sikuli.RegionObserver_swigregister
RegionObserver_swigregister(RegionObserver)

class EventManager(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, EventManager, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, EventManager, name)
    __repr__ = _swig_repr
    __swig_getmethods__["addObserver"] = lambda x: _sikuli.EventManager_addObserver
    if _newclass:addObserver = staticmethod(_sikuli.EventManager_addObserver)
    __swig_getmethods__["observe"] = lambda x: _sikuli.EventManager_observe
    if _newclass:observe = staticmethod(_sikuli.EventManager_observe)
    __swig_getmethods__["stop"] = lambda x: _sikuli.EventManager_stop
    if _newclass:stop = staticmethod(_sikuli.EventManager_stop)
    def __init__(self): 
        this = _sikuli.new_EventManager()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _sikuli.delete_EventManager
    __del__ = lambda self : None;
EventManager_swigregister = _sikuli.EventManager_swigregister
EventManager_swigregister(EventManager)

def EventManager_addObserver(*args):
  return _sikuli.EventManager_addObserver(*args)
EventManager_addObserver = _sikuli.EventManager_addObserver

def EventManager_observe(*args):
  return _sikuli.EventManager_observe(*args)
EventManager_observe = _sikuli.EventManager_observe

def EventManager_stop():
  return _sikuli.EventManager_stop()
EventManager_stop = _sikuli.EventManager_stop

SKIP = _sikuli.SKIP
RETRY = _sikuli.RETRY
ABORT = _sikuli.ABORT
class SikuliUI(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SikuliUI, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SikuliUI, name)
    __repr__ = _swig_repr
    def __init__(self): 
        if self.__class__ == SikuliUI:
            _self = None
        else:
            _self = self
        this = _sikuli.new_SikuliUI(_self, )
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _sikuli.delete_SikuliUI
    __del__ = lambda self : None;
    def handleFindFailedException(self, *args): return _sikuli.SikuliUI_handleFindFailedException(self, *args)
    def handleMatchFound(self, *args): return _sikuli.SikuliUI_handleMatchFound(self, *args)
    __swig_getmethods__["set"] = lambda x: _sikuli.SikuliUI_set
    if _newclass:set = staticmethod(_sikuli.SikuliUI_set)
    __swig_setmethods__["sikuliUI"] = _sikuli.SikuliUI_sikuliUI_set
    __swig_getmethods__["sikuliUI"] = _sikuli.SikuliUI_sikuliUI_get
    if _newclass:sikuliUI = _swig_property(_sikuli.SikuliUI_sikuliUI_get, _sikuli.SikuliUI_sikuliUI_set)
    def __disown__(self):
        self.this.disown()
        _sikuli.disown_SikuliUI(self)
        return weakref_proxy(self)
SikuliUI_swigregister = _sikuli.SikuliUI_swigregister
SikuliUI_swigregister(SikuliUI)

def SikuliUI_set(*args):
  return _sikuli.SikuliUI_set(*args)
SikuliUI_set = _sikuli.SikuliUI_set

import inspect
import sys
import __main__

def Region__enter__(self): 
   self._global_funcs = {}
   for name in dir(self):
      if inspect.ismethod(getattr(self,name)) and __main__.__dict__.has_key(name):
         self._global_funcs[name] = __main__.__dict__[name]
         #print "save " + name + " :" + str(__main__.__dict__[name])
         __main__.__dict__[name] = eval("self."+name)
   return self

def Region__exit__(self, type, value, traceback): 
   for name in self._global_funcs.keys():
      __main__.__dict__[name] = self._global_funcs[name]

Region.__enter__ = Region__enter__
Region.__exit__ = Region__exit__


def Screen_exposeAllMethods(self, mod):
   exclude_list = [ 'class', 'classDictInit', 'clone', 'equals', 'finalize', 
                   'getClass', 'hashCode', 'notify', 'notifyAll', 
                   'toGlobalCoord', 'toString',
                   'capture', 'selectRegion']
   dict = sys.modules[mod].__dict__
   for name in dir(self):
      if inspect.ismethod(getattr(self,name)) \
         and name[0] != '_' and name[:7] != 'super__' and \
         not name in exclude_list:
         #if DEBUG: print "expose " + name
         dict[name] = eval("self."+name)
         #__main__.__dict__[name] = eval("self."+name)
Screen._exposeAllMethods = Screen_exposeAllMethods


def initSikuli():
   dict = globals()
   dict['SCREEN'] = Screen()
   dict['SCREEN']._exposeAllMethods(__name__)
   #print "Sikuli is initialized." 
  
   
initSikuli()
   



